# Generated by Django 3.2.11 on 2024-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '',
                'db_table': 'user',
            },
        ),
    ]
